 % Fichier pour définir le RdP

function [pns] = pn_def()

pns.PN_name = '2 cloture à 3 parties reliées';

% set of places %
pns.set_of_Ps = {'E1' , 'F1', 'G1', ... % parties de la cloture initiale 
                 'E2' , 'F2', 'G2' %, ... %
%                  'S1','S2' ... % substrats
                 }; 

% set of transitions %
% ATTENTION les transitions des clotures doivent commencer par un T
pns.set_of_Ts = {'T11', 'T12' , 'T13' , ... % transitions/fonctions de la cloture initiale 
                 'T21', 'T22' , 'T23' , ...
                 'VE12','VE21', ... 
                 'VF12','VF21', ... 
                 'VG12','VG21', ...
                 }; 
             
% set of arcs %
pns.set_of_As = {'E1'  , 'T11' ,1 , ... % cloture initiale E1-F1-G1
                 'T11' , 'E1'  ,1 , ...
                 'T11' , 'F1'  ,1 , ...
                 'F1'  , 'T12' ,1 , ...  
                 'T12' , 'F1'  ,1 , ...
                 'T12' , 'G1'  ,1 , ...
                 'G1'  , 'T13' ,1 , ...
                 'T13' , 'G1'  ,1 , ...
                 'T13' , 'E1'  ,1 , ...
                 ...
                 'E2'  , 'T21' ,1 , ... % cloture initiale E2-F2-G2
                 'T21' , 'E2'  ,1 , ...
                 'T21' , 'F2'  ,1 , ...
                 'F2'  , 'T22' ,1 , ...  
                 'T22' , 'F2'  ,1 , ...
                 'T22' , 'G2'  ,1 , ...
                 'G2'  , 'T23' ,1 , ...
                 'T23' , 'G2'  ,1 , ...
                 'T23' , 'E2'  ,1 , ...
                 ...
                 'E1'  , 'VE12',1 , ... % reseau des variants
                 'VE12', 'E2'  ,1 , ... 
                 'E2'  , 'VE21',1 , ...  % variation inverse  
                 'VE21', 'E1'  ,1 , ... 
                 ...
                 'F1'  , 'VF12',1 , ...
                 'VF12', 'F2'  ,1 , ...
                 'F2'  , 'VF21',1 , ...
                 'VF21', 'F1'  ,1 , ...
                 ...         
                 'G1'  , 'VG12',1 , ...
                 'VG12', 'G2'  ,1 , ...
                 'G2'  , 'VG21',1 , ...
                 'VG21', 'G1'  ,1 %, ...
                 ...
%                  'F1'  , 'VE12',1 , ...  % F1 contraint la variation d'E1
%                  'VE12', 'F1'  ,1 , ...
%                  'F2'  , 'VE21',1 , ...  % F2 contraint la variation d'E2
%                  'VE21', 'F2'  ,1 , ... 
%                                          % E1 contraint la variation de F1
                                         % E2 contraint la variation de F2
                                         % G1 contraint la variation de E1
                                         % G2 contraint la variation de E2
                                         % ......
                 ...
%                  'S1' , 'T11' ,1 , ...  % substrats en commun avec tt les clotures
%                  'S2' , 'T12' ,1  ...
                 }; 
end

% dans PNS:
% global_Vplaces = jetons qui résident dans des transitions lancées




           